import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import Narbar from "../components/Narbar";
import "./globals.css";
import Footer from "../components/Footer";

const kanit = Kanit({ subsets: ["latin"], weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <Narbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
